version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: taskscheduler
      POSTGRES_PASSWORD: taskscheduler
      POSTGRES_DB: taskscheduler
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
volumes:
  postgres_data:
  redis_data: