version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: taskscheduler
      POSTGRES_PASSWORD: taskscheduler
      POSTGRES_DB: taskscheduler
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  task-scheduler-api:
    build:
      context: .
      dockerfile: task_scheduler_api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://taskscheduler:taskscheduler@postgres:5432/taskscheduler
      REDIS_URL: redis://redis:6379
      RUST_LOG: debug

  queue-populator:
    build:
      context: .
      dockerfile: queue_populator/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://taskscheduler:taskscheduler@postgres:5432/taskscheduler
      REDIS_URL: redis://redis:6379
      RUST_LOG: debug

  task-executor:
    build:
      context: .
      dockerfile: task_executor/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://taskscheduler:taskscheduler@postgres:5432/taskscheduler
      REDIS_URL: redis://redis:6379
      RUST_LOG: debug

  task-failure-watcher:
    build:
      context: .
      dockerfile: task_failure_watcher/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://taskscheduler:taskscheduler@postgres:5432/taskscheduler
      REDIS_URL: redis://redis:6379
      RUST_LOG: debug

  task-recurrence-manager:
    build:
      context: .
      dockerfile: task_recurrence_manager/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://taskscheduler:taskscheduler@postgres:5432/taskscheduler
      REDIS_URL: redis://redis:6379
      RUST_LOG: debug

volumes:
  postgres_data:
  redis_data:
