[package]
name = "scheduler_core"
version = "0.1.0"
edition = "2024"

[dependencies]
# Core dependencies needed for shared logic
tokio = { version = "1", features = ["rt", "macros", "time"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "macros", "chrono", "uuid", "json"] }
redis = { version = "0.25", features = ["tokio-comp"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
config = "0.14"
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1.0" # Good for defining custom error types
cron = "0.12"