[package]
name = "scheduler_core"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async runtime
tokio = { version = "1.44.2", features = ["full"] }

# Database (PostgreSQL)
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# Key-Value Store (Redis)
redis = { version = "0.29.5", features = ["tokio-comp"] }

# Serialization/Deserialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# Date and Time
chrono = { version = "0.4.40", features = ["serde"] }

# UUIDs
uuid = { version = "1.16.0", features = ["v4", "serde"] }

# Error Handling
thiserror = "2.0.12"

# Logging (optional but recommended)
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# Cron parsing (optional, for schedule parsing later)
cron = "0.15"
