[package]
name = "task_scheduler_api"
version = "0.1.0"
edition = "2024"

[dependencies]
# Depend on the shared core library (using a path dependency within the workspace)
scheduler_core = { path = "../scheduler_core" }

# rocket-web for building the API
rocket = { version = "0.5.1", features = ["secrets"] }
rocket_sync_db_pools = { version = "0.1.0-rc.4" }
