app:
  name: "Task Scheduler"
  version: "0.1.0"
  environment: "local"

server:
  host: "0.0.0.0"
  port: 8000
  workers: 4

redis:
  url: "redis://localhost:6379"
  pool_size: 10

database:
  url: "postgres://postgres:postgres@localhost:5432/task_scheduler"
  pool_size: 5

logging:
  level: "info"
  format: "json" 