app:
  environment: "local"
  debug: true

server:
  port: 8000

redis:
  url: "redis://localhost:6379"

database:
  url: "postgres://postgres:postgres@localhost:5432/task_scheduler"

logging:
  level: "debug"
